# Generated by Django 4.1 on 2022-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_id_html_alter_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_html',
            field=models.CharField(default='files', max_length=20),
        ),
    ]
