# Generated by Django 4.1 on 2022-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_id_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_html',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='files', upload_to=''),
        ),
    ]
